# Numpy

## Parte 1

In [ ]:
import numpy as np

In [ ]:
l = [4, 8, 2, 12, 5, 8, 0]

arr = np.array(l)
arr

In [ ]:
np.zeros()
np.arange()
np.random.random()

colab.research.google.com

In [ ]:
l = [1, 2, 3, 4]
arr1 = np.array(l)

arr1

In [ ]:
np.zeros((3,2)) #tuplas
#primeiro a linha, segundo as colunas)

In [ ]:
np.arange(0, 11)

# list(range(0, 11)) # é igual

In [ ]:
arr_range = np.arange(1,11)

arr_range

In [ ]:
type(arr_range)

In [ ]:
np.random.random((3,3))

### Exercícios

1. Crie um array com 4 linhas e 3 colunas com valores aleatórios

In [ ]:
np.random.random((4,3))

2. Crie um array com 5 colunas e 10 linhas inicializados com zeros.

In [ ]:
np.zeros((10,5))

3. Crie um array com valores inteiros 3 linhas e 5 colunas com valores aleatórios

In [ ]:
np.random.randint(10, 31, size=(3,5))

## Parte 2

In [ ]:
# Array 3D

arr1_2d = np.array([[1, 2], [3, 4]])
arr2_2d = np.array([[5, 6], [7, 8]])
arr3_2d = np.array([[9, 2], [3, 4]])

arr_3d = np.array([arr1_2d, arr2_2d, arr3_2d])

arr_3d

In [ ]:
# Array 4D

np.array([arr_3d, arr_3d])

In [ ]:
np.zeros((3, 4, 2))

In [ ]:
arr.shape

In [ ]:
# Array (shape) -> achatar

arr = np.zeros((2, 4))
print(arr)

arr.shape

In [ ]:
# Array (flatten) -> achatando

arr.flatten()

In [ ]:
# Reshaping - mudando as dimensões

arr = np.array([[3, 4, 2], [8, 11, 5]])
arr.reshape((3,2))

In [ ]:
arr_3d.reshape((4,3))

### Exercícios

1. Reduza o array (5, 7) a apenas uma dimensão

In [ ]:
a57 = np.random.random((5,7))
a57 = a57.flatten()

a57

2. Considerando que você é uma organizadora de um jogo de bingo. Crie um array que irá representar a cartilha desses jogos de bingo. Os números da suas cartelas variam de 1 e 30, e você terá 10 participantes. Cada cartela terá 12 números (4, 3).

Crie um array que represente esse jogo

In [ ]:
bingo = np.random.randint(1, 31, size=(10, 4, 3))
bingo

3. Faça o reshape das suas cartelas para que haja 5 cartelas de 4 linhas e 6 colunas

In [ ]:
bingo.reshape((5, 4, 6))

## Parte 3

Python:
- int
- float

Numpy:
- np.int64
- np.int32
- np.float64
np.float32

In [ ]:
np.array([2.14, 6.25, 160.87, 8.4]).dtype

# dtype('float64')

In [ ]:
np.array([2, 6, 160, 8]).dtype

# dtype('int64')

In [ ]:
np.array(["Hello", "Coder", "Girls"]).dtype

# dtype('<U5')

In [ ]:
# dtype como arguento

arr_float32 = np.array([2.14, 6.25, 160.87], dtype=np.float32)

arr_float32


In [ ]:
# Conversão

arr_vf = np.array([[True, False], [True, True]], dtype=np.bool8)

arr_vf.astype(np.int32)

In [ ]:
# Coerção

np.array(["Pedra", False, 42, 42.42])

# array(['Pedra', 'False', '42', '42.42'], dtype='<U32')

### Hierarquia de coerção

Float é dominante sobre Int

Inteiro é dominante sobre Booleanos

### Tipo de dados em um numpy array

In [ ]:
np.array([5.4, 6.7, 2.1]).dtype

In [ ]:
np.array([5, 6, 2]).dtype

In [ ]:
np.array(["Hello", "Oi", "WoMakersCode"]).dtype

In [ ]:
np.array([3, 4, 2.1]).dtype

In [ ]:
x = np.array([3, 4, 2.1])

x[1] #transformado para float

In [ ]:
np.array([True, False, 3]).dtype

In [ ]:
x.astype(np.int32)

In [ ]:
x

Transformando uma variável:

In [ ]:
vf = np.array([True, False, 3])
vf # transformou em int

In [ ]:
vf.astype(np.float32) # transformou em float

In [ ]:
vf.astype(np.bool_) # transformou em bool

## Parte 4

Index em um array de 1 dimensão

In [ ]:
arr = np.array ([2, 4, 6, 8])
arr[2]

### Para indexar um array de coluna e linha, usar:

Exemplo de seleção apenas um dado:

carleta_bingo[1, 3]
- Primeiro valor é linha = 1
- Segundo valor é coluna = 3

Exemplo de seleção de uma linha inteira:

cartela_bingo[0]
- Primeira linha

Exemplo de seleção de uma coluna inteira:

cartela_bingo[:, 1]
- Segunda coluna

In [ ]:
# Fatiar (slicing) um array de 1 dimensão

arr = np.array([2, 4, 6, 8, 10])
arr[2:4]

Exemplo de fatiamento dentro da cartela:

cartela_bingo[1:3, 0:2]

Exemplo de Ordenar (sorting) um array:

np.sort(cartela_bingo)

### Eixos (axis)

axis 0 = coluna / vertical
axis 1 = linha / horizontal

np.sort(cartela_bingo, axis=0)

np.sort(cartela_bingo, axis=1)

In [ ]:
arr = np.array([2, 4, 6, 7, 8])
arr[1]

In [ ]:
arr[0]

In [ ]:
cartela_bingo = np.array([[16, 10, 3, 15],
                          [14, 23, 17, 27],
                          [6, 19, 3, 1],
                          [10, 4, 18, 19]])
cartela_bingo

In [ ]:
# Slice

cartela_bingo[:, 1] #Coluna inteira

In [ ]:
# Reshape

cartela_bingo[:, 1].reshape((4, 1))

In [ ]:
# Somente a primeira linha

cartela_bingo[0]

In [ ]:
# Sort dentro da cartela
# considerando o eixo vertical

np.sort(cartela_bingo) # considerando o eixo vertical

In [ ]:
# Sort considerando eixo 0

np.sort(cartela_bingo, axis=0)

## Exercício

### 1.2 Explorando Ecossistemas:

Como bióloga marinha, me encontrei em uma expedição nas profundezas do Oceano Pacífico, onde estávamos estudando a biodiversidade e a saúde dos recifes de coral. O catálogo abaixo demonstra dados das espécies encontradas, considere a seguinte ordem de colunas:

*** ID da espécie, quantidade de representantes encontrados, profundeza, tamanho médio da espécie ***

- Selecione a segunda coluna com a quantidade de espécies encontradas e adicione um array como 'qtd_especies'
- De qtd_especies selecione apenas as primeiras 3 quantidades e print
- Print as 5 últimas quantidades de espécies
- Crie u array que contenha apenas os tamanhos das especies e orgene por ordem crescente

In [ ]:
especies = np.array([[747, 89, 33, 5],
                    [633, 123, 32, 12],
                    [501, 22, 49, 2],
                    [297, 56, 69, 22],
                    [613, 64, 27, 7],
                    [295, 84, 29, 14],
                    [691, 105, 72, 16],
                    [229, 103, 35, 5],
                    [374, 124, 70, 1]])
especies

In [ ]:
qtd_especies = especies[:, 1]
qtd_especies

In [ ]:
print(qtd_especies[0:3])

In [ ]:
especies.shape # indicação de quantidade (linhas, colunas)

In [ ]:
qtd_especies[-5:] # últimas 5 espécies

In [ ]:
np.sort(especies[:, 3]) # quarta coluna por ordem crescente

In [ ]:
np.sort(especies[:, 3])[::-1] # por ordem decrescente

## Parte 5

### Filtrando arrays

### Indexação sofisticada (fancy indexing) e máscara (mask) em array 2D

In [ ]:
pessoas_id_idade = np.array([[1, 22], [2, 1], [3, 27], [4, 26]])

pessoas_id_idade[:, 1] % 2 == 0 # todas as linhas da segunda coluna - quais são divisíveis por 2 (valore par)

### Indexação sofisticada (fancy indexing) e máscara (mask)

Boolean mask
- Retorna um array de verdadeiros e falsos

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
mask = arr % 2 == 0
mask

Fancy Indexing
- Retorna os valores do array quando pasado a máscara

In [ ]:
arr[mask]

### Fancy indexing e np.where()

Fancy indexing
- Retorna os valores do array quando passado a máscara

In [ ]:
cartela_bingo

In [ ]:
np.where(cartela_bingo % 3 == 0)

np.where()
- Retorna um array de indices
- Cria uma matriz com base em se os elementos correspondem ou não a uma condição

In [ ]:
pessoas_id_idade = np.array([[1, 22], [2, 1], [3, 27], [4, 26]])

np.where(pessoas_id_idade[:, 1] % 2 == 0)

Buscar e substituir

In [ ]:
np.where(cartela_bingo % 3 == 0, "", cartela_bingo)

## Exercício

### 1.2 Ainda usando o Array de espécies marítmas

- Usando um index booleano crie um array que contém os dados da maior espécie encontrada (considerando o seu tamanho), esse valor corresponde ao valor 22.
- Usando fency index faça um array que contém apenas dados da espécie com ID 297
- Usando np.where() faça um array com a linha com dados correspondentes a espécie com 105 representantes encontrados.
- Considere a profundeza em que o espécie foi encontrada substitua valores maiores que 60 por "Profundo"

In [ ]:
especies

In [ ]:
especies[:, 3] == 22

In [ ]:
maior_especie = especies[especies[:, 3] == 22]
maior_especie

In [ ]:
mask_297 = especies[:, 0] == 297
especies[mask_297]

In [ ]:
np.where(especies[:, 1] == 105)

In [ ]:
especies[np.where(especies[:, 1] == 105)]

In [ ]:
especies[:, 2] > 60

In [ ]:
np.where(especies[:, 2] > 60, "Profundo", especies[:, 2])

## Parte 6

### Adicionando e removendo dados do array

### Concatenação

Concatenando linhas

In [ ]:
arrv1 = np.random.randint(10, size=(3, 2))
arrv1

In [ ]:
arrv2 = np.array([["Peras", "Morango"]])
arrv2

In [ ]:
# concatenando
np.concatenate((arrv1, arrv2))

Concatenando colunas - axis

In [ ]:
arrv1

In [ ]:
arro1 = np.array(['Uva', 'Abacaxi', 'Laranja']).reshape((3, 1))
arro1

In [ ]:
np.concatenate((arrv1, arro1), axis=1)

Tentar concatenar quando colunas x colunas ou linhas x linhas não são iguais, da erro.

np.concatenate tem que levar em consideração as dimensões


### Deletando com axis = 0
Linhas

np.delete(sala_espera, 2, axis=0)

### Deletando com axis = 1
Colunas

np.delete(sala_espera, 1, axis=1)

### Deletando sem axis

np.delete(sala_espera, 1)

Sem as dimensões é que retorna um array sem dimensões nenhuma e fora de forma

### Cálculos com array

Métodos de agregação de dados

- .sum()
- .min()
- .max()
- .mean() = média
- .comsum()

EX:
- acidentes.sum() - soma tudo
- acidentes.sum(axis=0) - soma somente as linhas (resultado por coluna)
- acidentes.sum(axis=1) - soma somente as colunas (resultado por linha)
- acidentes.min() - aparece o minimo considerando todo o array
- acidentes.max(axis=0) - aparece o máximo da linha (resultado por coluna)

Keepdims, manter as mesmas dimensões

EX:
- acidentes.mean(axis=0, keepdims=True) - Ele mantém as mesmas dimensões

Soma cumulativa = cumsum

Acontece uma soma cumulativa = aparece todos os dados mas agora com soma cumulativa

acidentes.cumsum(axis = 0)

plt.plot(np.arange(1, 6), acidentes.cumsum(axis=0), label=['Cliente 1','Cliente 2', 'Cliente 3'])

plt.legent()

plt.show()

## Exercícios

Cartela de Bingo

In [ ]:
cartela_bingo

In [ ]:
cartela_bingo1 = cartela_bingo[:3]
cartela_bingo1

In [ ]:
cartela_bingo2 = cartela_bingo[-1:]
cartela_bingo2

In [ ]:
np.concatenate((cartela_bingo1, cartela_bingo2))

In [ ]:
cartela_bingo == np.concatenate((cartela_bingo1, cartela_bingo2))

Sala de Espera

In [ ]:
sala_espera = np.array([['5', '30', '1', 'Alice'],
                        ['6', '29', '1', 'Bob'],
                        ['7', '35', '3', 'Cristina'],
                        ['8', '34', '3', 'Luiz']])
sala_espera

In [ ]:
np.delete(sala_espera, 3, axis=0)

### 1.3 Ainda no conjunto 'especies'.

- Adicione mais 2 espécies no array: [[204, 10, 40, 12], [392, 11, 81, 11]]
- Adicione mais uma coluna no array original agora com o número de espécies encontradas com que indica se o animal enxerga ou não: [0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0]
- Faça um array com todas as espécies menos as com ID: 623, 116, 613

In [ ]:
especies

In [ ]:
novas_especies = np.array([[204, 10, 40, 12],
                           [392, 11, 81, 11]])
novas_especies

In [ ]:
especies = np.concatenate((especies, novas_especies))

In [ ]:
ver = np.array([0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0]).reshape(11,1)
ver

In [ ]:
ver.shape

In [ ]:
especies.shape

In [ ]:
np.concatenate((especies, ver), axis=1)

## Parte 7

### Operações com vetorização

### Comparação operações - Python vs NumPy

Ao realizar a soma de elementos em um array utilizando o NumPy, a operação não ocorre de forma individual para cada elemento; em vez disso, ela é realizada de maneira simultânea para todos os elementos do array.

In [ ]:
arr = np.array([[1, 2], [4, 5]])

for linha in range(0, arr.shape[0]):
    for coluna in range(0, arr.shape[1]):
        arr[linha][coluna] +=3

arr

In [ ]:
arr = np.array([[1, 2], [4, 5]])
arr += 3
arr

### Sintax Numpy

No NumPy, a sintaxe é otimizada: empregamos um sinal de adição e indicamos ao NumPy o número único que desejamos adicionar a todos os elementos do array. Na linguagem matemática, esse único número é comumente denonimado escala. Podemos utilizar uma sintaxe semelhante para multiplicar um array por um escalar.

In [198]:
arr = np.array([[1, 2], [4, 5]])
arr += 3
arr

array([[4, 5],
       [7, 8]])

In [199]:
arr2 = np.array([[1, 2], [4, 5]])

arr2 * 5

array([[ 5, 10],
       [20, 25]])

### Adicionando 2 array

O NumPy permite operações vetorizadas entre arrays do mesmo formato. Na adição de dois arrays com o mesmo formato, o NumPy realiza a operação elemento por elemento, somando cada elemento do primeiro array ao elemento correspondente no segundo array.

In [200]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2, 2], [0, 0, 1]])
a + b

array([[2, 4, 5],
       [4, 5, 7]])

### Multiplicando 2 arrays

O mesmo conceito se aplica à multiplicação, subtração e divisão de dois arrays no NumPy. Nessas operações, os elementos nas posições correspondentes de cada array são multiplicados, subtraídos ou divididos entre si.

In [201]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2, 2], [0, 0, 1]])
a * b

array([[1, 4, 6],
       [0, 0, 6]])

### Operações booleanas

Embora as operações vetorizadas se destacam em operações matemáticas, seu aproveitamento se estende por todo o NumPy. Anteriormente, exploramos o uso dessas operações para criar máscaras booleanas e filtrar arrays.

In [202]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a > 3

array([[False, False, False],
       [ True,  True,  True]])

### Vetorizando código Python (np.vectorize)

np.vectorize transforma funções Python regulares em funções vetorizadas. Isso significa que podemos aplicar eficientemente uma função a cada elemento de um array NumPy sem nos preocuparmos com loops explícitos. É muito útil quando precisamos operar em arrays, mas temos funções projetadas para operar em valores únicos.

In [203]:
arr = np.array(['Hello', 'meninas', 'coders'])
len(arr) > 0

True

In [204]:
vetorizar_len = np.vectorize(len)

vetorizar_len(arr) > 5

array([False,  True,  True])

In [205]:
def minha_funcao(x):
    return x**2 + 3*x +1

vetorizada_funcao = np.vectorize(minha_funcao)

array_original = np.array([1, 2, 3, 4, 5])

resultado = vetorizada_funcao(array_original)

resultado

array([ 5, 11, 19, 29, 41])

### Broadcasting (transmissão)

Broadcasting (transmissão) refere-se à capacidade do NumPy de lidar com operações entre arrays de diferentes formas e tamanhos durante operações aritméticas. O Broadcasting permite que o NumPy execute essas operações mesmo quando as dimensões dos arrays não são as mesmas, seguindo um conjunto de regras específicas.

In [206]:
arr2 = np.array([[1, 2], [4, 5]])
arr2 *5

array([[ 5, 10],
       [20, 25]])

In [207]:
arr_3x3 = np.array([[1, 2],
                    [4, 5],
                    [7, 8]])
arr_3x3

array([[1, 2],
       [4, 5],
       [7, 8]])

In [208]:
arr_3x1 = np.array([1, 0, -1]).reshape((3,1))
arr_3x1

array([[ 1],
       [ 0],
       [-1]])

In [209]:
arr_3x3 + arr_3x1

array([[2, 3],
       [4, 5],
       [6, 7]])

Linhas

In [210]:
arr10 = np.arange(10).reshape((2, 5))
arr5 = np.array([0, 1, 2, 3, 4])
arr10.shape, arr5.shape

((2, 5), (5,))

In [211]:
arr10 + arr5

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

Colunas

In [212]:
arr10 = np.arange(10).reshape((2, 5))
arr2 = np.array([0, 1]).reshape((2, 1))
arr10.shape, arr2.shape

((2, 5), (2, 1))

In [213]:
arr10 + arr2

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

### Outras operações

A aplicação da mesma lógica estende-se à multiplicação, subtração e divisão! Ao multiplicar por uma coluna, cada elemento dessa coluna é multiplicado pelos elementos correspondentes em ambas as colunas do array maior. Da mesma forma, ao subtrair uma linha, cada elemento dessa linha é subtraído dos elementos correspondentes em ambas as linhas do array maior.

In [217]:
arr10 = np.arange(10).reshape((2, 5))
arr2 = np.array([2, 1]).reshape((2, 1))
arr10.shape, arr2.shape

((2, 5), (2, 1))

In [218]:
arr10 / arr2

array([[0. , 0.5, 1. , 1.5, 2. ],
       [5. , 6. , 7. , 8. , 9. ]])

In [219]:
arr10 * arr2

array([[0, 2, 4, 6, 8],
       [5, 6, 7, 8, 9]])

### Salvando arquivos em NumPy

Dados numpy podem ser salvos em diferentes formatos:
- .npy (NumPy Binary)
- .txt (Txt/CSV)
- .h5 (HDF5 - Hierarchical Data Format)
- .json (JSON)
- .csv (Comma-Separated Values)
- .parquet (Apache Parquet)


Por quê usar arquivos .npy


1 - Eficiencia de Armazenamento: O formato binário utilizado é altamente eficiente em termos de armazenamento, sendo especialmente útil para grandes conjuntos de dados reduzinho os requisitos de espaço e melhorando a velocidade de operações de leitura e escrita.
2 - Presenvaçã de Informações: Ao salvar um array como .npy, o formato inclui informações cruciais sobre o tipo de dados e a forma do array. Isso garante que, ao carrega-lo posteriormente, a estrutura original seja recriada com precisão, evitando perda de informações.
3 - Carregamento Rápido: O carregamento de dados a partir de um arquivo .npy é geralmente mais rápido do que em formatos de texto. Isso se deve à eficiente serialização e deserialização dos dados, resultando em tempos de carregamento mais curtos.
4 - Compatibilidade com NumPy: O formato .npy é específico do NumPy, proporcionando compatibilidade sólida com outras ferramentas e bibliotecas baseadas em NumPy. Isso estabelece uma maneira padronizada e confiável de armazenar e compartilhar arrays de diferentes projetos e colaboradores.


In [ ]:
# Carregando

arr = np.load('arr10.npy')

In [ ]:
# Salvando

arr10 = np.arange(10).reshape((2, 5))
arr10

In [ ]:
np.save('arr10.npy', arr10)